controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# config/routes.yaml

livre_sorted:
    path: /livres/sorted
    controller: App\Controller\LivreController::getLivresSorted
    methods: [GET]

livres_par_auteur:
    path: /api/livres/par_auteur
    controller: App\Controller\LivreController::getLivresByAuteur
    methods: [GET]